version: '3.8'

services:
  api:
    build: ./
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
